---
# roles/install-keybase/tasks/install-ubuntu.yml

- name: Add keybase signing key
  apt_key:
    id: '47484E50656D16C7'
    keyserver: keyserver.ubuntu.com

- name: Add keybase repository
  apt_repository:
    repo: deb http://prerelease.keybase.io/deb stable main
    filename: keybase
    update_cache: yes
