---
# roles/install-1password/tasks/main.yml

- name: import install-fedora if distribution is fedora
  import_tasks: install-fedora.yml
  when: ansible_distribution == "Fedora"

- name: import install-ubuntu if distribution is ubuntu
  import_tasks: install-ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- name: install 1password
  ansible.builtin.package:
    name: 1password
    state: present
