repos:
- repo: git://github.com/pre-commit/pre-commit-hooks
  sha: v1.2.3
  hooks:
    - id: check-merge-conflict
    - id: check-byte-order-marker
    - id: detect-aws-credentials
    - id: check-yaml
    - id: check-executables-have-shebangs
    - id: detect-private-key
- repo: git://github.com/detailyang/pre-commit-shell
  sha: 1.0.2
  hooks:
    - id: shell-lint
