#!/bin/bash

#dump all environment variables except git related ones
alias fullenv='( set -o posix ; set ) | grep -v "__git"'

#open a URL in chrome from the command line
alias open='google-chrome "$@"'

#VSCode
alias code='__code'

#IP addresses
alias remoteip='curl http://checkip.amazonaws.com'
alias localip='__localip'

#go to git dir
[[ -d "${HOME}/mygit" ]] && alias mg='cd "${HOME}"/mygit; ls' || alias mg='echo "${HOME}"/mygit is not a dir. Set this up first..."

#set volume from command line
alias volume="__volume $1"

#start http server in current dir
alias server='__server'

#lazy cd'ing
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'

#prefer mosh
if [[ -f ${HOME}/bin/mosh.sh ]]; then
  alias ssh=${HOME}/bin/mosh.sh
elif [[ -f /usr/bin/mosh ]]; then
  alias ssh=/usr/bin/mosh
fi

alias fixmouse='xkbset ma 60 10 10 5 2'

alias less='less -Ri'

#alias packer to packer because of https://github.com/mitchellh/packer/issues/1117
[[ -f ${HOME}/bin/packer ]] && alias packr=${HOME}/bin/packer || alias packr='echo "${HOME}"/bin/packer is not there. Install Packer first???'
