#!/bin/bash

#dump all environment variables except git related ones
alias fullenv='( set -o posix ; set ) | grep -v "__git"'

#open a URL in chrome from the command line
alias open='google-chrome "$@"'

#VSCode
alias code='__code'

#IP addresses
alias remoteip='curl http://checkip.amazonaws.com'
alias localip='__localip'

#go to git dir
alias mg='cd "${HOME}"/mygit; ls'

#set volume from command line
alias volume="__volume $1"

#start http server in current dir
alias server='__server'

#lazy cd'ing
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'

#prefer mosh
if [[ -f ${HOME}/bin/mosh.sh ]]; then
  alias ssh=${HOME}/bin/mosh.sh
elif [[ -f /usr/bin/mosh ]]; then
  alias ssh=/usr/bin/mosh
fi

alias fixmouse='xkbset ma 60 10 10 5 2'

alias less='less -Ri'
