#!/bin/bash

#bash environment
shopt -s extglob;
shopt -s histappend;

#Load in our dotfiles
for file in ~/.{aliases,functions,exports,bash_prompt}; do
  [[ -r "$file" ]] && [[ -f "$file" ]] && source "$file" || echo "Could not source ${file}. What up?!" 
done
unset file

#source specific files and functions
[[ -n "${NVM_DIR}" ]] && [[ -s "${NVM_DIR}/nvm.sh" ]] && \
  source "${NVM_DIR}/nvm.sh"

[[ -s "${HOME}/.avn/bin/avn.sh" ]] && source "${HOME}/.avn/bin/avn.sh" || echo "avn not installed or did you run 'avn setup' yet?"

[[ -s "${HOME}/.rvm/scripts/rvm" ]] && source "${HOME}/.rvm/scripts/rvm" || echo "rvm not installed or install went wrong"

