#!/bin/bash

#bash environment
shopt -s extglob;
shopt -s histappend;

#Load in our dotfiles
for file in ~/.{aliases,functions,exports,bash_prompt}; do
  [[ -r "$file" ]] && [[ -f "$file" ]] && source "$file"
done
unset file

#source specific files and functions
[[ -n ${NVM_DIR} ]] && [[ -s "${NVM_DIR}/nvm.sh" ]] && \
  source "${NVM_DIR}/nvm.sh"
[[ -s "${HOME}/.rvm/scripts/rvm" ]] && source "${HOME}/.rvm/scripts/rvm"
[[ -s "${HOME}/.avn/bin/avn.sh" ]] && source "${HOME}/.avn/bin/avn.sh"
