#!/usr/bin/env bash

export LC_ALL=en_GB.UTF-8

#more colours in terminal
if [[ "${COLORTERM}" = "gnome-*" && "${TERM}" = "xterm" ]] && infocmp gnome-256color >/dev/null 2>&1; then
	export TERM='gnome-256color';
elif infocmp xterm-256color >/dev/null 2>&1; then
	export TERM='xterm-256color';
fi;

#<3 vim
export EDITOR='/usr/bin/vim'

#history settings
export HISTSIZE=1000000;
export HISTFILESIZE=$HISTSIZE;
export HISTCONTROL=ignoreboth:erasedups;
export PROMPT_COMMAND="history -n; history -w; history -c; history -r; $PROMPT_COMMAND";
export HISTIGNORE="ls:cd:cd -:pwd:exit:date:* --help:* help:* --version";

#local scripts
[[ -d "${HOME}/bin" ]] && pathappend ${HOME}/bin || \
  echo 'No bindir found at '${HOME}/bin'. Not adding to $PATH.'

#golang exports
[[ -f "/usr/local/go/bin/go" ]] && export GOROOT="/usr/local/go" && \
  pathappend ${GOROOT}/bin || echo "GOROOT not set. Is Go installed?"

[[ -d "${HOME}/golang" ]] && { [[ ":${GOPATH}:" != *":${HOME}/golang:"* ]] && \
  export GOPATH="${HOME}/golang${GOPATH:+":${GOPATH}"}"; }

[[ -d "${GOPATH}/bin" ]] && pathappend ${GOPATH}/bin || \
  echo 'Go bindir not found at '${GOPATH}/bin'. Not adding to $PATH.'

#haskell/cabal exports - disabled while using shellcheck from packages
#[[ -d "${HOME}/.cabal/bin" ]] && pathappend ${HOME}/.cabal/bin || \
#  echo 'Cabal bindir not found at '${HOME}/.cabal/bin'. Is cabal installed?'

#nvm exports
[[ -d "${HOME}/.nvm" ]] && export NVM_DIR="${HOME}/.nvm" || \
  echo 'nvm not found in '${HOME}'. Not setting $NVM_DIR.'

#rvm exports
[[ -f "${HOME}/.rvm/bin" ]] && pathappend ${HOME}/.rvm/bin
