---
- hosts: localhost
  connection: local

  tasks:
    - name: load vars
      include_vars: main.yml

    - name: load distribution vars
      include_vars: "{{ ansible_distribution | lower }}.yml"

    - import_tasks: tasks/dotfiles.yml

    - name: setup shell environment
      include_role:
        name: setup-shell-env

    - name: install pre-requisites
      include_role:
        name: "prereqs-{{ ansible_distribution | lower }}"
        apply:
          become: yes

    - name: install common packages
      include_role:
        name: packages-common
        apply:
          become: yes

    - name: setup git
      include_role:
        name: setup-git

    - name: install-keybase
      include_role:
        name: install-keybase
        apply:
          become: yes

    # - name: install 1password
    #   include_role:
    #     name: install-1password
    #     apply:
    #       become: yes

    - name: install-docker
      include_role:
        name: geerlingguy.docker
        apply:
          become: yes
      vars:
        docker_users:
          - amo
      when: container_dev | bool

    - name: install-google-cloud-sdk
      include_role:
        name: install-google-cloud-sdk
        apply:
          become: yes
      when: gcp_dev | bool

    - name: install-cloudflare-tools
      include_role:
        name: install-cloudflare-tools
        apply:
          become: yes
      when: cf_tools | bool
