#!/bin/bash

__localip() {
  ip addr show $(route | grep default | awk '{print $8}') | grep inet | awk '{print $1" "$2}' | cut -d\/ -f1
}

# Start an HTTP server from a directory, optionally specifying the port
__server() {
  local port="${1:-8000}"
  sleep 1 && open "http://localhost:${port}/" &
  # Set the default Content-Type to `text/plain` instead of `application/octet-stream
  # And serve everything as UTF-8 (although not technically correct, this doesn’t break anything for binary files)
  python -c $'import SimpleHTTPServer;\nmap = SimpleHTTPServer.SimpleHTTPRequestHandler.extensions_map;\nmap[""] = "text/plain";\nfor key, value in map.items():\n\tmap[key] = value + ";charset=UTF-8";\nSimpleHTTPServer.test();' "$port"
}

#set volume from command line
__volume() {
  local volumeicon

  if [[ -z $1 ]]; then
    amixer -D pulse sget Master
  else
    amixer -D pulse sset Master $1%
    if [[ $1 == 'off' ]] || [[ $1 == 0 ]]; then
      volumeicon="audio-volume-muted.png"
    elif [[ $1 -ge 1 && $1 -lt 50 ]]; then
      volumeicon="audio-volume-low.png"
    elif [[ $1 -lt 90 ]]; then
      volumeicon="audio-volume-medium.png"
    elif [[ $1 -le 100 ]]; then
      volumeicon="audio-volume-high.png"
    else
      echo "what the hell are you trying to do?!"
    fi
    notify-send -i /usr/share/icons/Adwaita/48x48/status/${volumeicon} "Volume set to $1"
  fi
}

pathappend() {
  for ARG in "$@"
  do
    if [[ -d "$ARG" ]] && [[ ":$PATH:" != *":$ARG:"* ]]; then
        PATH="${PATH:+"$PATH:"}$ARG"
    fi
  done
}

pathprepend() {
  for ARG in "$@"
  do
    if [[ -d "$ARG" ]]  && [[ ":$PATH:" != *":$ARG:"* ]]; then
        PATH="$ARG${PATH:+":$PATH"}"
    fi
  done
}

bootstrap_git_repo() {
  if [[ -d .git ]] || [[ $(git rev-parse --is-inside-git-dir &> /dev/null) ]]; then
    [[ -f .gitignore ]] || echo -n "[INFO]: no .gitignore found"
    [[ -f .editorconfig ]] || echo -n "[INFO]: no .editorconfig found"
    [[ -f .pre-commit-config.yaml ]] || echo -n "[INFO]: no .pre-commit-config.yaml found"
    pre-commit install
  else
    echo "are you sure this is a git dir?"
  fi
}
