#!/bin/bash

#dump all environment variables except git related ones
alias fullenv='( set -o posix ; set ) | grep -v "__git"'

#open a URL in chrome from the command line
command -v google-chrome &> /dev/null && alias open='google-chrome "$@"' || \
  alias open='echo "google-chrome is not installed"'

#IP addresses
alias remoteip='curl http://checkip.amazonaws.com'
alias localip='__localip'

#go to git dir
[[ -d "${HOME}/mygit" ]] && alias mg='cd "${HOME}"/mygit; ls' || \
  alias mg='echo "${HOME}"/mygit is not a dir. Set this up first...'

#set volume from command line
alias volume="__volume $1"

#start http server in current dir
alias server='__server'

#lazy cd'ing
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'

#prefer mosh
if [[ -x ${HOME}/bin/mosh.sh ]]; then
  alias ssh=${HOME}/bin/mosh.sh
elif [[ -x /usr/bin/mosh ]]; then
  alias ssh=/usr/bin/mosh
fi

alias less='less -Ri'

#alias packer to packr because of
#https://github.com/mitchellh/packer/issues/1117
[[ -x /usr/local/bin/packer ]] && alias packer.io=/usr/local/bin/packer || \
  alias packer.io='echo /usr/local/bin/packer is not there. Install Packer first???'

#alias netdata
[[ -x /usr/sbin/netdata ]] && alias netdata='open "http://localhost:19999"' || \
  alias netdata='echo "Is netdata installed?  ¯\_(ツ)_/¯"'
