---
- name: add bash related file symlinks
  ansible.builtin.file:
    src: "{{ playbook_dir }}/files/dotfiles/_bash_{{ item }}"
    dest: "{{ ansible_env.HOME }}/.bash_{{ item }}"
    state: link
    force: yes
  with_items:
    - aliases
    - completions
    - exports
    - functions
    - npm_config
    - profile
    - prompt
    - ruby_config

- name: add bash rc type file symlinks
  ansible.builtin.file:
    src: "{{ playbook_dir }}/files/dotfiles/_{{ item }}rc"
    dest: "{{ ansible_env.HOME }}/.{{ item }}rc"
    state: link
    force: yes
  with_items:
    - bash
    - input
    - nvm
    - vim

- name: add vim directory symlink
  ansible.builtin.file:
    src: "{{ playbook_dir }}/files/vim/"
    dest: "{{ ansible_env.HOME }}/.vim"
    state: link
    force: yes
