---
# roles/prereqs-ubuntu/tasks/main.yml

- name: install ubuntu specific prerequisite packages
  ansible.builtin.package:
    name:
      - apt-transport-https
      - ca-certificates
      - gnupg
    state: latest
