---
# roles/packages-common/tasks/main.yml

- name: setup git ppa on ubuntu
  ansible.builtin.apt_repository:
    repo: ppa:git-core/ppa
  when: ansible_distribution == "Ubuntu"

- name: Install the common packages I want
  ansible.builtin.package:
    name:
      - curl
      - git
      - gnome-tweaks
      - "{{ vim_package_name }}"
    state: latest

# - google-chrome
# - 1password
