---
# roles/packages-common/tasks/main.yml

- name: import packages-common-fedora if distribution is fedora
  import_tasks: packages-common-fedora.yml
  when: ansible_distribution == "Fedora"

- name: import packages-common-ubuntu if distribution is ubuntu
  import_tasks: packages-common-ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- name: Install the common packages I want
  ansible.builtin.package:
    name:
      - curl
      - git
      - gnome-tweaks
      - meld
      - "{{ vim_package_name }}"
    state: latest

# - google-chrome
# - 1password
